#!/usr/bin/env ruby

#pathogen - to manage all the other plugins neatly


git_bundles = [
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/msanders/snipmate.vim.git", #Textmate like snipplet funktion
  "git://github.com/scrooloose/nerdtree.git", #navigate and manipulate files
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git", #lots of Git goodness for Vim
  "git://github.com/tpope/vim-git.git",
	"git://github.com/pangloss/vim-javascript.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git", #various helpers from the vim-ruby project for rails
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git", #add, delete and change common pairs easily
	"git://github.com/tpope/vim-endwise.git", #automagically enter an 'end' as needed in Ruby files
	"git://github.com/commonthread/vim-vibrantink.git",
  "git://github.com/tpope/vim-vividchalk.git",
	"git://github.com/cschlueter/vim-molokai.git",
	"git://github.com/taq/vim-rspec.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tsaleh/vim-supertab.git",
	"git://github.com/Townk/vim-autoclose.git",
  "git://github.com/tsaleh/vim-tcomment.git", #a better fuzzy finder for opening files
  "git://github.com/vim-ruby/vim-ruby.git",
	"git://github.com/bingaman/vim-sparkup.git", #(like Zen Coding, but just seems to work more smoothly with vim)
  "git://repo.or.cz/vcscommand",
	"git://github.com/marcelinollano/vim-fuzzyfinder.git",
  "git://github.com/vim-bundles/fuzzyfinder.git",
  "git://github.com/borgand/ir_black.git",
	"git://github.com/chrismetcalf/vim-autocomplpop.git",
	#Conque is a Vim plugin which allows you to run interactive programs, such as bash on linux or powershell.exe on Windows, inside a Vim buffer. In other words it is a terminal emulator which uses a Vim buffer to display the program output. 
	"git://github.com/chrismetcalf/vim-conque.git"
#	"git://github.com/Shougo/neocomplcache"
]

vim_org_scripts = [
  ["IndexedSearch", "7062", "plugin"], #show total count number and current hit for searches
  ["gist", "12732", "plugin"], #add support for sending buffers to gist or editing gists via Vim
  ["jquery", "12107", "syntax"],
  ["bufexplorer", "12904", "zip"], #work better with buffers
  ["taglist", "7701", "zip"], #helpful source code browser
]

require 'fileutils'
require 'open-uri'

bundle_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundle_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts " Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts " Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.#{script_type == 'zip' ? 'zip' : 'vim'}")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    %x(unzip -d #{name} #{local_file})
  end
end
